var mystring;
var myNum;
var myBool;
var myVar;
// let strArr : string[];
var numArr;
var boolArr;
var strArr;
var strNumTuple;
mystring = "Hey its Hello from the TS world";
myNum = 22;
myBool = false;
myVar = true;
strArr = ["Hello ", "World !"];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['hello', 4];
var myVoid = null;
var myNull = undefined;
var myUndefined = undefined;
console.log(myVoid);
